name: Bug report
description: Create a report to help us improve
labels: bug
body:
- type: markdown
  attributes:
    value: "Thanks for taking the time to file this report! To begin, fill in the details below."
- type: markdown
  attributes:
    value: "## Bug Details"
- type: textarea
  attributes:
    label: Describe the bug
    description: "A clear and concise description of what the bug is."
  validations:
    required: true
- type: textarea
  attributes:
    label: Replication steps
    description: "How can we replicate the behaviour described in the above section? Be specific."
    value: |
      1. Go to '...'
      2. Click on '....'
      3. Scroll down to '....'
      4. See error
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected behavior
    description: "A clear and concise description of what you expected to happen."
  validations:
    required: true
- type: upload
  attributes:
    label: Screenshots
    description: |
      If applicable, add screenshots to help explain your problem.
      It is recommended you press F3 twice to show the "basic" debug overlay so that helpful debugging information is included in your screenshot.

      A size limit of 10MB applies. Images must be in one of the following formats: `.png`, `.jpg`, `.jpeg`, `.gif`, `.svg`, or `.webp`
  validations:
    accept: ".png,.jpg,.jpeg,.gif,.svg,.webp"

- type: markdown
  attributes:
    value: "## System Details"

- type: input
  attributes:
    label: Operating System
    description: "What is the operating system of your device?"
    placeholder: "e.g. Windows 10, iOS 26.2"
  validations:
    required: true
- type: input
  attributes:
    label: Bedrock World Editor Version
    description: "What version of Bedrock World Editor did this bug occur on?"
    placeholder: "e.g. 1.0.0-beta.27"
  validations:
    required: true


- type: markdown
  attributes:
    value: "## Other Details"
- type: textarea
  attributes:
    label: Additional Context
    description: "Add any other context about the problem here."
